# Role to reboot the Raspberry.
---
- name: 'Reboot RPi'
  shell: sleep 5 && shutdown -r now
  async: 1
  poll: 0
  become: true

- name: "Wait for server to come back"
  wait_for_connection:
  args:
    delay: 15
    timeout: 120
